#!/usr/bin/env bash
source ./settings
declare -Ar colors=(
	[red]='\e[31m'
 	[green]='\e[32m'
 	[brown]='\e[33m'
 	[blue]='\e[34m'
 	[purple]='\e[35m'
 	[cyan]='\e[36m'
 	[gray]='\e[37m'
)
readonly DEAFULT='\e[0m'

cleanUp(){
	rm -r "$dir"
}
createConfig(){
	local CONFIGWR

	printf "Choose a color: (Enter it's name.)\n"
	printf  "1:${colors[red]} red $DEAFULT\n"
	printf  "2:${colors[green]} green $DEAFULT\n"
	printf  "3:${colors[brown]} brown $DEAFULT\n"
	printf  "4:${colors[blue]} blue $DEAFULT\n"
	printf  "5:${colors[purple]} purple $DEAFULT\n"
	printf  "6:${colors[cyan]} cyan $DEAFULT\n"
	printf  "7:${colors[gray]} gray $DEAFULT\n"
	local chcolor
	read chcolor
	chcolor="${colors["$chcolor"]}"
	

	CONFIGWR="#!/usr/bin/env bash
COLORSET='$chcolor'"

	printf "%s\n" "$CONFIGWR" > settings
	COLORSET="$chcolor"

}
if ! [ -f settings ];then
	createConfig
fi
name=$(whoami)

dir=/tmp/"$name" 
if ! [ -d "$dir" ]; then
	mkdir "$dir"
fi
pipe="$dir"/pipe
if ! [ -f "$pipe" ]; then
	mkfifo "$pipe"
fi
chgrp chat "$pipe"
chmod 620 "$pipe"

readMsg(){
	while true; do
		cat "$pipe"
	done
}

trap cleanUp exit || trap cleanUp SIGINT
readMsg &
while true; do
	sendPat='^\/(\w+)\ (.+)'
	read -r input
	if [[ "$input" =~ $sendPat ]]; then
		user=${BASH_REMATCH[1]}
		msg=${BASH_REMATCH[2]}
		printf "%b%b%b: %s\n" "$COLORSET" "$name" "$DEAFULT" "$msg" > /tmp/"$user"/pipe
	fi

done
